export type Category = "old-testament" | "new-testament" | "general";
export type Difficulty = "easy" | "medium" | "hard";

export interface TriviaQuestion {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
  category: Category;
  difficulty: Difficulty;
  explanation: string;
}

export const triviaQuestions: TriviaQuestion[] = [

  // ─── EASY · GENERAL ────────────────────────────────────────────────────────
  {
    id: 1,
    question: "Who built the ark?",
    options: ["Moses", "Noah", "Abraham", "David"],
    correctIndex: 1,
    category: "general",
    difficulty: "easy",
    explanation: "God commanded Noah to build the ark to save his family and two of every living creature from the great flood (Genesis 6–7).",
  },
  {
    id: 2,
    question: "How many days and nights did it rain during the flood?",
    options: ["7", "12", "40", "100"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    explanation: "Rain fell for 40 days and 40 nights, flooding the entire earth (Genesis 7:12).",
  },
  {
    id: 3,
    question: "Who was the first man created by God?",
    options: ["Adam", "Enoch", "Cain", "Seth"],
    correctIndex: 0,
    category: "general",
    difficulty: "easy",
    explanation: "God formed Adam from the dust of the ground and breathed life into him (Genesis 2:7).",
  },
  {
    id: 4,
    question: "Where was Jesus born?",
    options: ["Jerusalem", "Nazareth", "Bethlehem", "Jericho"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    explanation: "Jesus was born in Bethlehem of Judea, fulfilling the prophecy in Micah 5:2 (Luke 2:4–7).",
  },
  {
    id: 5,
    question: "How many books are in the Bible?",
    options: ["52", "60", "66", "73"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    explanation: "The Protestant Bible contains 66 books — 39 in the Old Testament and 27 in the New Testament.",
  },
  {
    id: 6,
    question: "What is the first book of the Bible?",
    options: ["Exodus", "Psalms", "Genesis", "Numbers"],
    correctIndex: 2,
    category: "general",
    difficulty: "easy",
    explanation: "Genesis is the first book of the Bible. Its name means 'beginning' or 'origin.'",
  },
  {
    id: 7,
    question: "What is the last book of the Bible?",
    options: ["Jude", "Hebrews", "Acts", "Revelation"],
    correctIndex: 3,
    category: "general",
    difficulty: "easy",
    explanation: "Revelation (also called the Apocalypse of John) is the final book of the New Testament and of the entire Bible.",
  },

  // ─── EASY · OLD TESTAMENT ──────────────────────────────────────────────────
  {
    id: 8,
    question: "What did David use to defeat Goliath?",
    options: ["A sword", "A spear", "A sling and a stone", "A bow and arrow"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "easy",
    explanation: "David struck Goliath in the forehead with a stone from his sling, killing the Philistine giant (1 Samuel 17:49).",
  },
  {
    id: 9,
    question: "Who was swallowed by a great fish?",
    options: ["Peter", "Jonah", "Paul", "Elijah"],
    correctIndex: 1,
    category: "old-testament",
    difficulty: "easy",
    explanation: "Jonah was swallowed by a great fish after he fled from God's command to go to Nineveh. He remained inside three days and three nights (Jonah 1:17).",
  },
  {
    id: 10,
    question: "What body of water did the Israelites cross on dry land?",
    options: ["Dead Sea", "Mediterranean Sea", "Red Sea", "Sea of Galilee"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "easy",
    explanation: "God parted the Red Sea for Moses and the Israelites, and they crossed on dry ground while escaping from Pharaoh's army (Exodus 14).",
  },
  {
    id: 11,
    question: "What garden did Adam and Eve live in?",
    options: ["Garden of Gethsemane", "Garden of Eden", "Garden of Olives", "Garden of Sinai"],
    correctIndex: 1,
    category: "old-testament",
    difficulty: "easy",
    explanation: "God planted the Garden of Eden in the east and placed Adam there to tend and keep it (Genesis 2:8–15).",
  },
  {
    id: 12,
    question: "How many sons did Jacob have?",
    options: ["10", "11", "12", "14"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "easy",
    explanation: "Jacob had 12 sons who became the ancestors of the 12 tribes of Israel (Genesis 35:22–26).",
  },
  {
    id: 13,
    question: "Who led the Israelites out of Egypt?",
    options: ["Joshua", "Aaron", "Moses", "Abraham"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "easy",
    explanation: "God chose Moses to lead the Israelites out of slavery in Egypt during the Exodus (Exodus 3–14).",
  },

  // ─── EASY · NEW TESTAMENT ──────────────────────────────────────────────────
  {
    id: 14,
    question: "Who baptized Jesus?",
    options: ["Peter", "John the Baptist", "James", "Matthew"],
    correctIndex: 1,
    category: "new-testament",
    difficulty: "easy",
    explanation: "John the Baptist baptized Jesus in the Jordan River. As Jesus came up from the water, the Holy Spirit descended like a dove (Matthew 3:13–17).",
  },
  {
    id: 15,
    question: "What was Joseph's (Jesus' earthly father's) profession?",
    options: ["Fisherman", "Shepherd", "Carpenter", "Tax Collector"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "easy",
    explanation: "Joseph was a carpenter. The people of Nazareth referred to Jesus as 'the carpenter's son' (Matthew 13:55).",
  },
  {
    id: 16,
    question: "How many disciples did Jesus choose?",
    options: ["7", "10", "12", "40"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "easy",
    explanation: "Jesus chose 12 disciples, sometimes called apostles, who traveled with him and were commissioned to spread the gospel (Matthew 10:1–4).",
  },
  {
    id: 17,
    question: "Who denied Jesus three times before the rooster crowed?",
    options: ["James", "John", "Judas", "Peter"],
    correctIndex: 3,
    category: "new-testament",
    difficulty: "easy",
    explanation: "Peter denied knowing Jesus three times the night of Jesus' arrest, just as Jesus had predicted (Matthew 26:69–75).",
  },
  {
    id: 18,
    question: "What did Jesus turn water into at the wedding in Cana?",
    options: ["Milk", "Honey", "Wine", "Juice"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "easy",
    explanation: "Jesus' first recorded miracle was turning water into wine at a wedding in Cana of Galilee (John 2:1–11).",
  },
  {
    id: 19,
    question: "Who was the mother of Jesus?",
    options: ["Elizabeth", "Martha", "Mary", "Salome"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "easy",
    explanation: "The angel Gabriel appeared to Mary and announced that she would conceive and give birth to the Son of God (Luke 1:26–31).",
  },

  // ─── MEDIUM · GENERAL ──────────────────────────────────────────────────────
  {
    id: 20,
    question: "Which book is the longest in the Bible?",
    options: ["Genesis", "Isaiah", "Psalms", "Jeremiah"],
    correctIndex: 2,
    category: "general",
    difficulty: "medium",
    explanation: "Psalms is the longest book in the Bible with 150 chapters. It also contains the longest chapter (Psalm 119) and the shortest (Psalm 117).",
  },
  {
    id: 21,
    question: "Who wrote the majority of the New Testament letters?",
    options: ["Peter", "John", "Luke", "Paul"],
    correctIndex: 3,
    category: "general",
    difficulty: "medium",
    explanation: "Paul authored at least 13 letters in the New Testament, from Romans to Philemon, making him the most prolific NT writer.",
  },
  {
    id: 22,
    question: "What language was the New Testament originally written in?",
    options: ["Latin", "Hebrew", "Aramaic", "Greek"],
    correctIndex: 3,
    category: "general",
    difficulty: "medium",
    explanation: "The New Testament was written in Koine Greek, the common Greek dialect spoken throughout the Roman Empire in the first century.",
  },
  {
    id: 23,
    question: "Who was the first king of Israel?",
    options: ["David", "Solomon", "Saul", "Jeroboam"],
    correctIndex: 2,
    category: "general",
    difficulty: "medium",
    explanation: "Saul was anointed by Samuel and became Israel's first king. He reigned for 40 years before being succeeded by David (1 Samuel 10:24).",
  },
  {
    id: 24,
    question: "In which city did the early church first gather after Pentecost?",
    options: ["Antioch", "Rome", "Jerusalem", "Corinth"],
    correctIndex: 2,
    category: "general",
    difficulty: "medium",
    explanation: "After the Holy Spirit came at Pentecost, the first church was established in Jerusalem. Three thousand people were added in a single day (Acts 2).",
  },
  {
    id: 25,
    question: "What does the Hebrew word 'Amen' mean?",
    options: ["Praise God", "Hallelujah", "So be it / Truly", "Blessed"],
    correctIndex: 2,
    category: "general",
    difficulty: "medium",
    explanation: "'Amen' comes from a Hebrew root meaning 'firm' or 'certain.' It is used to affirm a statement as true — essentially 'so be it' or 'truly.'",
  },

  // ─── MEDIUM · OLD TESTAMENT ────────────────────────────────────────────────
  {
    id: 26,
    question: "Who was Moses' brother?",
    options: ["Joshua", "Aaron", "Caleb", "Miriam"],
    correctIndex: 1,
    category: "old-testament",
    difficulty: "medium",
    explanation: "Aaron was Moses' older brother. God appointed Aaron to be Moses' spokesman before Pharaoh (Exodus 4:14–16).",
  },
  {
    id: 27,
    question: "What were the first two birds Noah sent from the ark to find dry land?",
    options: ["A raven and a dove", "Two doves", "An eagle and a dove", "A raven and a sparrow"],
    correctIndex: 0,
    category: "old-testament",
    difficulty: "medium",
    explanation: "Noah first sent out a raven, then a dove. The dove returned with an olive branch on its second flight, signaling that the waters had receded (Genesis 8:6–11).",
  },
  {
    id: 28,
    question: "Who interpreted Pharaoh's dreams about seven fat and seven thin cows?",
    options: ["Daniel", "Jacob", "Joseph", "Moses"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "medium",
    explanation: "Joseph interpreted Pharaoh's dreams as seven years of abundance followed by seven years of famine. This led to his appointment as second-in-command over Egypt (Genesis 41).",
  },
  {
    id: 29,
    question: "Which judge of Israel was known for his extraordinary physical strength?",
    options: ["Gideon", "Samson", "Jephthah", "Deborah"],
    correctIndex: 1,
    category: "old-testament",
    difficulty: "medium",
    explanation: "Samson was empowered by God's Spirit and performed great feats of strength, including tearing a lion apart with his bare hands (Judges 14–16).",
  },
  {
    id: 30,
    question: "Whose city walls fell down after the Israelites marched around them?",
    options: ["Ai", "Jericho", "Hebron", "Gaza"],
    correctIndex: 1,
    category: "old-testament",
    difficulty: "medium",
    explanation: "God commanded Joshua to march the Israelites around Jericho for seven days. On the seventh day the walls collapsed and the city fell (Joshua 6).",
  },
  {
    id: 31,
    question: "Who anointed Saul as the first king of Israel?",
    options: ["Elijah", "Nathan", "Samuel", "Eli"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "medium",
    explanation: "The prophet Samuel anointed Saul with oil and declared him king over Israel as God had instructed him (1 Samuel 10:1).",
  },

  // ─── MEDIUM · NEW TESTAMENT ────────────────────────────────────────────────
  {
    id: 32,
    question: "What was the first miracle Jesus performed?",
    options: ["Walking on water", "Healing a blind man", "Turning water into wine", "Feeding the 5,000"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "medium",
    explanation: "Jesus' first recorded miracle was turning water into wine at a wedding celebration in Cana of Galilee (John 2:1–11).",
  },
  {
    id: 33,
    question: "Who was the tax collector that climbed a tree to see Jesus?",
    options: ["Matthew", "Zacchaeus", "Nicodemus", "Judas"],
    correctIndex: 1,
    category: "new-testament",
    difficulty: "medium",
    explanation: "Zacchaeus was a chief tax collector in Jericho who climbed a sycamore tree to see Jesus over the crowd. Jesus invited himself to Zacchaeus' home (Luke 19:1–10).",
  },
  {
    id: 34,
    question: "On which day of the week did Jesus rise from the dead?",
    options: ["Friday", "Saturday", "Sunday", "Monday"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "medium",
    explanation: "Jesus rose from the dead on the first day of the week (Sunday). This is why Christians gather to worship on Sundays (Matthew 28:1; Mark 16:2).",
  },
  {
    id: 35,
    question: "Who was chosen to replace Judas Iscariot as the twelfth apostle?",
    options: ["Stephen", "Barnabas", "Matthias", "Silas"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "medium",
    explanation: "After Judas betrayed Jesus and died, the apostles cast lots and Matthias was chosen to take his place among the Twelve (Acts 1:26).",
  },
  {
    id: 36,
    question: "What was Jesus doing when a storm arose on the Sea of Galilee?",
    options: ["Praying on the shore", "Walking on water", "Sleeping in the boat", "Teaching the disciples"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "medium",
    explanation: "Jesus was asleep on a cushion in the stern of the boat when a fierce storm hit. The disciples woke him, and he rebuked the wind and waves (Mark 4:37–39).",
  },
  {
    id: 37,
    question: "In the parable of the Prodigal Son, what did the younger son ask his father for before leaving?",
    options: ["His father's blessing", "His share of the inheritance", "A new robe", "Permission to travel"],
    correctIndex: 1,
    category: "new-testament",
    difficulty: "medium",
    explanation: "The younger son asked for his share of the estate early and then squandered it in reckless living in a far country (Luke 15:11–13).",
  },

  // ─── HARD · GENERAL ────────────────────────────────────────────────────────
  {
    id: 38,
    question: "What is the shortest verse in the Bible?",
    options: ["'God is love.'", "'Jesus wept.'", "'Pray continually.'", "'Rejoice always.'"],
    correctIndex: 1,
    category: "general",
    difficulty: "hard",
    explanation: "'Jesus wept.' (John 11:35) is the shortest verse in the English Bible. Jesus wept upon seeing the grief of Mary and those mourning Lazarus.",
  },
  {
    id: 39,
    question: "Who was the oldest man mentioned in the Bible?",
    options: ["Noah", "Adam", "Methuselah", "Enoch"],
    correctIndex: 2,
    category: "general",
    difficulty: "hard",
    explanation: "Methuselah lived 969 years, making him the oldest person recorded in the Bible (Genesis 5:27).",
  },
  {
    id: 40,
    question: "How many books are in the Old Testament?",
    options: ["33", "36", "39", "42"],
    correctIndex: 2,
    category: "general",
    difficulty: "hard",
    explanation: "The Old Testament contains 39 books in Protestant Bibles, spanning from Genesis to Malachi.",
  },
  {
    id: 41,
    question: "What was the name of Abraham's hometown before he moved to Canaan?",
    options: ["Babylon", "Nineveh", "Ur of the Chaldeans", "Haran"],
    correctIndex: 2,
    category: "general",
    difficulty: "hard",
    explanation: "Abraham was born and raised in Ur of the Chaldeans (in modern-day Iraq). God called him to leave and travel to the land of Canaan (Genesis 11:31).",
  },
  {
    id: 42,
    question: "What number is associated with 'the Beast' in Revelation?",
    options: ["444", "555", "616", "666"],
    correctIndex: 3,
    category: "general",
    difficulty: "hard",
    explanation: "The number 666 is called 'the number of the Beast' in Revelation 13:18. Scholars interpret it as a numerical code, likely referring to a Roman emperor.",
  },
  {
    id: 43,
    question: "Which of King Saul's daughters became the wife of David?",
    options: ["Merab", "Michal", "Rizpah", "Tamar"],
    correctIndex: 1,
    category: "general",
    difficulty: "hard",
    explanation: "Michal, Saul's younger daughter, loved David and was given to him as his wife (1 Samuel 18:20–27). She later helped David escape Saul's assassination attempt.",
  },

  // ─── HARD · OLD TESTAMENT ──────────────────────────────────────────────────
  {
    id: 44,
    question: "Who was the left-handed judge that assassinated King Eglon of Moab?",
    options: ["Gideon", "Samson", "Ehud", "Jephthah"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "hard",
    explanation: "Ehud, a left-handed Benjaminite, concealed a double-edged dagger on his right thigh and killed the oppressive Moabite king Eglon (Judges 3:15–21).",
  },
  {
    id: 45,
    question: "Which king of Judah was struck with leprosy by God?",
    options: ["Uzziah", "Hezekiah", "Josiah", "Manasseh"],
    correctIndex: 0,
    category: "old-testament",
    difficulty: "hard",
    explanation: "King Uzziah was struck with leprosy after he entered the temple to burn incense — a duty reserved for priests alone (2 Chronicles 26:16–21).",
  },
  {
    id: 46,
    question: "Who succeeded Elijah as prophet in Israel?",
    options: ["Isaiah", "Amos", "Elisha", "Micah"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "hard",
    explanation: "Elisha succeeded Elijah and received a double portion of his spirit. He witnessed Elijah taken to heaven in a whirlwind (2 Kings 2:9–14).",
  },
  {
    id: 47,
    question: "How many plagues did God send on Egypt before Pharaoh released Israel?",
    options: ["7", "8", "9", "10"],
    correctIndex: 3,
    category: "old-testament",
    difficulty: "hard",
    explanation: "God sent 10 plagues on Egypt: blood, frogs, gnats, flies, livestock disease, boils, hail, locusts, darkness, and the death of the firstborn (Exodus 7–12).",
  },
  {
    id: 48,
    question: "What was the name of Moses' father-in-law?",
    options: ["Eleazar", "Laban", "Jethro", "Amram"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "hard",
    explanation: "Jethro (also called Reuel) was a Midianite priest and the father of Zipporah, Moses' wife. He advised Moses to delegate leadership to capable judges (Exodus 18).",
  },
  {
    id: 49,
    question: "Who was the first child born in the Bible?",
    options: ["Abel", "Seth", "Cain", "Enoch"],
    correctIndex: 2,
    category: "old-testament",
    difficulty: "hard",
    explanation: "Cain was the firstborn child of Adam and Eve, the very first human birth recorded in Scripture (Genesis 4:1).",
  },

  // ─── HARD · NEW TESTAMENT ──────────────────────────────────────────────────
  {
    id: 50,
    question: "On what island was the apostle John exiled when he wrote Revelation?",
    options: ["Malta", "Cyprus", "Patmos", "Crete"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "hard",
    explanation: "John was exiled to the island of Patmos in the Aegean Sea 'because of the word of God and the testimony of Jesus.' There he received the visions recorded in Revelation (Revelation 1:9).",
  },
  {
    id: 51,
    question: "Who fell asleep and tumbled out of a window while Paul was preaching?",
    options: ["Eutychus", "Trophimus", "Timothy", "Silas"],
    correctIndex: 0,
    category: "new-testament",
    difficulty: "hard",
    explanation: "Eutychus fell from a third-floor window in Troas while Paul preached late into the night. Paul went down, embraced him, and he was restored to life (Acts 20:9–12).",
  },
  {
    id: 52,
    question: "What was the name of the high priest who questioned Jesus before his crucifixion?",
    options: ["Annas", "Caiaphas", "Ananias", "Zechariah"],
    correctIndex: 1,
    category: "new-testament",
    difficulty: "hard",
    explanation: "Caiaphas was the high priest that year and led the council that condemned Jesus. He declared it was better for one man to die for the people (Matthew 26:57; John 11:49–50).",
  },
  {
    id: 53,
    question: "Who was the Roman governor who sentenced Jesus to death?",
    options: ["Herod Antipas", "Pontius Pilate", "Felix", "Festus"],
    correctIndex: 1,
    category: "new-testament",
    difficulty: "hard",
    explanation: "Pontius Pilate, the Roman prefect of Judea, ordered Jesus' crucifixion despite believing him innocent. He symbolically washed his hands of the matter (Matthew 27:24–26).",
  },
  {
    id: 54,
    question: "What was the name of the place where Jesus was crucified?",
    options: ["Bethany", "Gethsemane", "Golgotha", "Emmaus"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "hard",
    explanation: "Golgotha, meaning 'Place of the Skull' (also called Calvary in Latin), was the hill outside Jerusalem where Jesus was crucified (Matthew 27:33).",
  },
  {
    id: 55,
    question: "For how many days did Jesus appear to his disciples after his resurrection?",
    options: ["3", "7", "40", "50"],
    correctIndex: 2,
    category: "new-testament",
    difficulty: "hard",
    explanation: "Jesus appeared to his disciples over a period of 40 days after his resurrection, speaking about the kingdom of God, before ascending into heaven (Acts 1:3).",
  },
];

export const wordSearchWords = ["JESUS", "MOSES", "DAVID", "NOAH", "FAITH", "GRACE", "PRAYER", "BIBLE", "ANGEL", "PSALM"];

export const kidsGameItems = [
  { id: "lion", icon: "🦁", name: "Lion" },
  { id: "dove", icon: "🕊️", name: "Dove" },
  { id: "fish", icon: "🐟", name: "Fish" },
  { id: "lamb", icon: "🐑", name: "Lamb" },
  { id: "snake", icon: "🐍", name: "Snake" },
  { id: "donkey", icon: "🐴", name: "Donkey" },
];

export const homeFAQs = [
  { q: "Are these Bible games completely free?", a: "Yes! All games on Bible Games Online are 100% free to play. There are no hidden fees or subscriptions required." },
  { q: "Do I need to create an account to play?", a: "No account is needed. You can jump right in and start playing immediately without any registration." },
  { q: "Are these games suitable for children?", a: "Absolutely. We have a dedicated Kids Games section with simple, engaging activities, and all our content is family-friendly." },
  { q: "Can I play on my mobile phone?", a: "Yes, our website is fully responsive and designed to work seamlessly on desktops, tablets, and smartphones." },
  { q: "Do you add new questions to the trivia games?", a: "We regularly update our database with new questions across all difficulty levels to keep the challenges fresh." }
];
